name: Publish Docker image on push
on: [push]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build cert-controller
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: hongyaa/rainbond-cert-controller
          tag_with_ref: true
          target: cert-controller
      - name: Build cert-checker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: hongyaa/rainbond-cert-checker
          tag_with_ref: true
          target: cert-checker  
      - name: Update Docker Hub Description
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKER_HUB_USERNAME }}
          pass: ${{ secrets.DOCKER_HUB_ACCOUNT_PASSWORD }}
          slug: hongyaa/rainbond-cert-controller
          readme: ./README.md
          description: true
